[package]
name = "simple-handout"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["chillcicada" "moeleak"]
license = "MIT"
description = "A simple handout template."
repository = "https://github.com/moeleak/simple-handout-template"
keywords = ["book", "handout", "template"]
categories = ["book"]
exclude = [".*", "example"]
compiler = "0.14.2"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
